name: Push images to DockerHub
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    strategy:
      matrix:
        colors: [red, green, blue]
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build image
      uses: docker/build-push-action@v2
      with:
        build-args: |
          color=${{ matrix.colors }}
        tags: camandel/whoami:${{ matrix.colors }}
        
    - name: push
      run: docker push camandel/whoami:${{ matrix.colors }}

    - name: tag and push latest image
      if: matrix.colors == 'red'
      run: docker tag camandel/whoami:red camandel/whoami:latest && docker push camandel/whoami:latest
     
